### ISSUE TITLE
Missing dependency - defold-timer

### ISSUE THREAD

**Issue by vovs03** [britzl/tweetfighter#2]
# ⚠️ Missing dependency - defold-timer

Björn, Hi again. I'm new to _defold_ & _Lua_. I'm clonned this repo to try run it on MacOs & learn it under microscope more detaily. 

- [x] I have only one question in start: "Is defold-timer(repo) was closed forever?" 
  - [x] Project was integrated to _Defold_ & new link: [timer API](https://defold.com/ref/timer/) `https://defold.com/ref/timer/`

Info about new :link: link I found after searching in [forum](https://forum.defold.com/t/defold-timer-is-missing-solved/60381)

P.s. - question has another side now...

**Comment by britzl** [comment]
Thank you for reporting. I haven't opened this project in quite some time, and we have integrated the timer solution in Defold. I have updated the project to reflect this. You can now build and run it from Defold.

I also uploaded a playable version here: https://britzl.github.io/TweetFighter

**Comment by vovs03** [comment]
Bjorn, I really admire the work you do. Thank you very much.
